---
releases:
- name: collectd
  sha1: 89d9afbb4e682f31e745f07bd40ff569d347343f
  #FIXME: Once the pull request on paas-collectd-boshrelease
  # is completed, this URL can be replaced with the github URL
  # where it will be stored permanently. The SHA-1 should be the
  # same
  # [1] https://github.com/alphagov/paas-collectd-boshrelease/pull/1
  url: https://s3-eu-west-1.amazonaws.com/mt-state/collectd-0.4.tgz
  #url: https://github.com/alphagov/paas-collectd-boshrelease/releases/download/0.4/collectd-0.4.tgz

jobs:
- name: bosh
  templates:
  - {name: collectd, release: collectd}

properties:
  collectd:
    hostname_prefix: bosh_
    interval: (( grab meta.collectd.interval ))
    config: (( grab meta.collectd.config ))
